### ISSUE TITLE
LSDOSystemTools mising?

### ISSUE THREAD

**Issue by decvalts** [LSDtopotools/LSDMappingTools#1]
I couldn't find this in the repo - it gets imported in LSDMap_BasicMapping.py

**Comment by decvalts** [comment]
Found it in a different repo, sorry: https://github.com/LSDtopotools/LSDAutomation

**Comment by simon-m-mudd** [comment]
LSDOsystemTools is used in a lot of different packages. Since I don't want a bunch of different versions I keep the master copy in one place (LSDAutomation). I'll try to update the readme to reflect the location of this package.
