### ISSUE TITLE
Visualising slope-area data

### ISSUE THREAD

**Issue by fclubb** [LSDtopotools/LSDMappingTools#10]
Start working on scripts to visualise slope-area data (try both raw and binned).  Things that would be good to add in:

- Separate different tributaries (can use the source key)
- Separate different basins
- Identifying breaks in concavity

**Comment by fclubb** [comment]
Now working so that we get a different plot for each basin. Will add in colour-coding by source node later on today. At the moment it just uses the raw data, but will also plot up the binned data.

**Comment by simon-m-mudd** [comment]
Note that I have got some code for selecting sources and colouring them: have a look in LSDPlottingTools/LSDMap_ChiPlotting.py and see, e.g., 
BasicChannelPlotGridPlotCategories
The code here makes a fixed colourmap:

```
    # make a color map of fixed colors
    NUM_COLORS = 15

    this_cmap = plt.cm.Set1
    cNorm  = colors.Normalize(vmin=0, vmax=NUM_COLORS-1)
    plt.cm.ScalarMappable(norm=cNorm, cmap=this_cmap)
    channel_data = [x % NUM_COLORS for x in these_data]

    ax.scatter(easting,Ncoord,s=0.5, c=channel_data,norm=cNorm,cmap=this_cmap,edgecolors='none')
```

and there are also bits of code in there for masking data and labeling both sources and basins.

**Comment by fclubb** [comment]
Nice, I've added that in. Hopefully this means that we can produce a basic channel plot that plots them in plan view over a raster, and the colour scheme should stay consistent on the slope area plots.
![bailey_dem_10m_sa_plot_basin0](https://cloud.githubusercontent.com/assets/12732264/26720028/f865ed20-4786-11e7-83ed-08184de62a8a.png)
