### ISSUE TITLE
Knickpoint plotting

### ISSUE THREAD

**Issue by fclubb** [LSDtopotools/LSDMappingTools#11]
We need to add in some plotting functions for nice plots of knickpoints.  I've made a bit of a start on this, so I'll add this in to the repository now, then @bgailleton and I can update it as we go.

**Comment by bgailleton** [comment]
Definitely a good idea, I'll write this down when I'll have few time!

**Comment by fclubb** [comment]
I've added my initial script for plotting the knickpoints to LSDMappingTools - it's called analyse_knickpoints.py.
At the moment it is standalone, I'm going to port it into mapping tools soon. So at the moment I use pandas to load in the csv, since it's nice to select the column headers that way:

    column_lists = []
    df = read_MChi_file(DataDirectory, csv_name, kp_threshold)
    for column_name in columns:
        column_values = list(df[column_name])
        column_lists.append(column_values)
    return column_lists

Would be good to plot:
* Elevation against flow distance
* Magnitude vs. elevation

I'm guessing you already have some plotting scripts @bgailleton, so let's consolidate them so we're not reinventing the wheel! We can also have the raster plots in here.

**Comment by fclubb** [comment]
Elevation against flow distance: will maybe add some channel profiles in here.  So far:
* Points coloured by channel source
* Size represents knickpoint magnitude
![combined_kp_elevations_28](https://cloud.githubusercontent.com/assets/12732264/26782528/559517b8-49f4-11e7-853e-150b7bf3f12a.png)

**Comment by simon-m-mudd** [comment]
So at the moment it looks like every channel just has loads of knickpoints. The visualisations look great! Now we need to ensure the algorithm is being more selective...

**Comment by bgailleton** [comment]
I will have the new knickpoint output file ready tomorrow hopefully, it will really be easier to deal with. 
Maybe Python will be more adapted to sort the data from the csv file containing every informations?

**Comment by simon-m-mudd** [comment]
Do you mean have the csv contain all the segment edges and then we use python to select the important knickpoints? Yes, I think that is a good idea.

**Comment by bgailleton** [comment]
yes ! ok let's do this

**Comment by fclubb** [comment]
Yes at the moment in the Python script I'm just selecting the knickpoints based on an arbitrary magnitude threshold - it would be good to think about a better way to select them. It should be easy to change this in the python code

**Comment by bgailleton** [comment]
I am adapting the python code to the new csv output, then I may change the way it processes data as the following: rather than reading the csv file each time, we could load it at the beginning, then sort it as following before calling the plotting function?
PointData= read_Mchi_file(...)
PointData= select_data("drainage area", operator = ">", value = 5000) # This is an example and not codded yet, but ill do it asap
PointData= select_data("diff", operator = "=<", value = 50)
...
plot_knickpoint_elevation(...)

It requires slightly more coding but it gives us more freedom to play with the data?

**Comment by fclubb** [comment]
Sounds good, yes it would be better to just load the point data as a function and then we can pass it as a parameter to each plotting script.  The functions at the start of the analyse_knickpoints.py script were for when I was using pandas to load the data without the PointData object, so we can probably get rid of them.

**Comment by bgailleton** [comment]
I am currently adapting everything and adding the possibility to load a pandas dataframe directly as a PointData Object, it should make things easier for sorting in this case.
It should be easier because we will process the data separately to extract the outliers, the basins, ...
