### ISSUE TITLE
Font size error in LSDMappingTools_test.py

### ISSUE THREAD

**Issue by rodti** [LSDtopotools/LSDMappingTools#24]
Running `LSDMappingTools_test.py 1` I get the following error from matplotlib:

`RuntimeError: In FT2Font: Could not set the fontsize`

I managed to fix this by changing line 79 of the LSDMappingTools_test.py script from:

`names = [fm.FontProperties(fname=fname).get_name() for fname in flist]`

to

`names = [fm.FontProperties(fname=fname).get_family() for fname in flist]`

**Comment by simon-m-mudd** [comment]
I can't reproduce this error in the docker container, but the fix above doesn't affect the behaviour of the routine so I have made this update.
